# Generated by Django 5.2.4 on 2025-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_table1'),
    ]

    operations = [
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=40)),
                ('age2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='table3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name3', models.CharField(max_length=30)),
                ('age3', models.IntegerField()),
            ],
        ),
    ]
