# Generated by Django 5.2.4 on 2025-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_table2_table3'),
    ]

    operations = [
        migrations.CreateModel(
            name='table4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name4', models.CharField(max_length=80)),
                ('age4', models.IntegerField()),
            ],
        ),
    ]
